export enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RECORD_ALREADY_EXISTS = 'RECORD_ALREADY_EXISTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  USER_LOCKED_OUT = 'USER_LOCKED_OUT',
  ZOD_ERROR = 'ZOD_ERROR',
  INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  INVALID_RECORD = 'INVALID_RECORD'
}
