export enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_LOCKED_OUT = 'USER_LOCKED_OUT',
  ZOD_ERROR = 'ZOD_ERROR',
  INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED',
  INVALID_TOKEN = 'INVALID_TOKEN'
}
