// This file is auto-generated by @hey-api/openapi-ts

export type PostAuthRegisterData = {
  /**
   * User registration details
   */
  requestBody?: {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    sex: 'male' | 'female' | 'other';
    birthDate: string;
  };
};

export type PostAuthRegisterResponse = {
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  role: 'admin' | 'user';
  sex: 'male' | 'female' | 'other';
  birthDate: string;
  storageSpaceInMB: string;
  usedStorageInBytes: string;
};

export type PostAuthLoginData = {
  /**
   * User login details
   */
  requestBody?: {
    email: string;
    password: string;
  };
};

export type PostAuthLoginResponse = {
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  role: 'admin' | 'user';
  sex: 'male' | 'female' | 'other';
  birthDate: string;
  storageSpaceInMB: string;
  usedStorageInBytes: string;
};

export type $OpenApiTs = {
  '/auth/register': {
    post: {
      req: PostAuthRegisterData;
      res: {
        /**
         * Success
         */
        200: {
          email: string;
          username: string;
          firstName: string;
          lastName: string;
          role: 'admin' | 'user';
          sex: 'male' | 'female' | 'other';
          birthDate: string;
          storageSpaceInMB: string;
          usedStorageInBytes: string;
        };
        /**
         * Error
         */
        400: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        401: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        402: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        403: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        404: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        405: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        406: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        407: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        408: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        409: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        410: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        411: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        412: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        413: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        414: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        415: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        416: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        417: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        418: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        421: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        422: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        423: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        424: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        425: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        426: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        428: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        429: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        431: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        451: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        500: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        501: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        502: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        503: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        504: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        505: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        506: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        507: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        508: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        510: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        511: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
      };
    };
  };
  '/auth/login': {
    post: {
      req: PostAuthLoginData;
      res: {
        /**
         * Success
         */
        200: {
          email: string;
          username: string;
          firstName: string;
          lastName: string;
          role: 'admin' | 'user';
          sex: 'male' | 'female' | 'other';
          birthDate: string;
          storageSpaceInMB: string;
          usedStorageInBytes: string;
        };
        /**
         * Error
         */
        400: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        401: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        402: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        403: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        404: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        405: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        406: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        407: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        408: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        409: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        410: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        411: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        412: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        413: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        414: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        415: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        416: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        417: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        418: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        421: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        422: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        423: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        424: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        425: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        426: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        428: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        429: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        431: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        451: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        500: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        501: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        502: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        503: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        504: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        505: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        506: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        507: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        508: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        510: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
        /**
         * Error
         */
        511: {
          code:
            | 'VALIDATION_ERROR'
            | 'USER_ALREADY_EXISTS'
            | 'INTERNAL_SERVER_ERROR'
            | 'INVALID_CREDENTIALS'
            | 'USER_LOCKED_OUT'
            | 'ZOD_ERROR'
            | 'INSUFFICIENT_STORAGE';
          message: string;
        };
      };
    };
  };
};
